/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取最新日志 */
        get: {
            parameters: {
                query?: {
                    /** @description 返回行数，默认 100，最大 1000 */
                    lines?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.LogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qb/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 测试 qBittorrent 连接 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.QBTestResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取设置（不返回密码） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.SettingsResponse"];
                    };
                };
            };
        };
        /** 更新设置，空密码保留原密码 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 设置 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["model.UpdateSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.SettingsResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订阅列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Subscription"][];
                    };
                };
            };
        };
        put?: never;
        /** 添加订阅并同步 qBittorrent */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 订阅 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["model.CreateSubscriptionRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Subscription"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新订阅并同步 qBittorrent */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 订阅 ID */
                    id: number;
                };
                cookie?: never;
            };
            /** @description 订阅 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["model.UpdateSubscriptionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Subscription"];
                    };
                };
            };
        };
        post?: never;
        /** 删除订阅及 qBittorrent RSS 配置 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 订阅 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新同步订阅到 qBittorrent */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 订阅 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["model.Subscription"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "model.CreateSubscriptionRequest": {
            customDirName?: string;
            regex?: string;
            rssUrl?: string;
            season?: number;
        };
        "model.LogResponse": {
            lines?: string[];
        };
        "model.QBTestResponse": {
            connected?: boolean;
            version?: string;
            webApiVersion?: string;
        };
        "model.SettingsResponse": {
            defaultCategory?: string;
            downloadRoot?: string;
            passwordSet?: boolean;
            qbUrl?: string;
            qbUsername?: string;
            rssInterval?: number;
        };
        "model.Subscription": {
            createdAt?: string;
            enabled?: boolean;
            id?: number;
            name?: string;
            rawTitle?: string;
            regex?: string;
            rssUrl?: string;
            ruleName?: string;
            saveDirName?: string;
            savePath?: string;
            season?: number;
            updatedAt?: string;
        };
        "model.UpdateSettingsRequest": {
            defaultCategory?: string;
            downloadRoot?: string;
            qbPassword?: string;
            qbUrl?: string;
            qbUsername?: string;
            rssInterval?: number;
        };
        "model.UpdateSubscriptionRequest": {
            enabled?: boolean;
            regex?: string;
            rssUrl?: string;
            saveDirName?: string;
            season?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
