/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/qb/test": {
    post: {
      responses: {
        /** OK */
        200: {
          schema: definitions["model.QBTestResponse"];
        };
      };
    };
  };
  "/settings": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["model.SettingsResponse"];
        };
      };
    };
    put: {
      parameters: {
        body: {
          /** 设置 */
          body: definitions["model.UpdateSettingsRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["model.SettingsResponse"];
        };
      };
    };
  };
  "/subscriptions": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["model.Subscription"][];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 订阅 */
          body: definitions["model.CreateSubscriptionRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["model.Subscription"];
        };
      };
    };
  };
}

export interface definitions {
  "model.CreateSubscriptionRequest": {
    customDirName?: string;
    regex?: string;
    rssUrl?: string;
  };
  "model.QBTestResponse": {
    connected?: boolean;
    version?: string;
    webApiVersion?: string;
  };
  "model.SettingsResponse": {
    defaultCategory?: string;
    downloadRoot?: string;
    passwordSet?: boolean;
    qbUrl?: string;
    qbUsername?: string;
    rssInterval?: number;
  };
  "model.Subscription": {
    createdAt?: string;
    enabled?: boolean;
    id?: number;
    name?: string;
    rawTitle?: string;
    regex?: string;
    rssUrl?: string;
    ruleName?: string;
    saveDirName?: string;
    savePath?: string;
    updatedAt?: string;
  };
  "model.UpdateSettingsRequest": {
    defaultCategory?: string;
    downloadRoot?: string;
    qbPassword?: string;
    qbUrl?: string;
    qbUsername?: string;
    rssInterval?: number;
  };
}

export interface operations {}

export interface external {}
