services:
  app:
    image: ghcr.io/hanngyaku/mikan-qb-rss:latest
    environment:
      DB_PATH: /app/data/app.db
      LOG_PATH: /app/data/app.log
      LISTEN_ADDR: :8081
    ports:
      - "8080:8081"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
