// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/logs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "获取最新日志",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "返回行数，默认 100，最大 1000",
                        "name": "lines",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LogResponse"
                        }
                    }
                }
            }
        },
        "/qb/rss-settings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "qbittorrent"
                ],
                "summary": "获取 qBittorrent RSS 全局设置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.QBRSSSettings"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "qbittorrent"
                ],
                "summary": "更新 qBittorrent RSS 全局设置",
                "parameters": [
                    {
                        "description": "RSS 设置",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.QBRSSSettings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.QBRSSSettings"
                        }
                    }
                }
            }
        },
        "/qb/test": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "qbittorrent"
                ],
                "summary": "测试 qBittorrent 连接",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.QBTestResponse"
                        }
                    }
                }
            }
        },
        "/settings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "获取设置（不返回密码）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SettingsResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "更新设置，空密码保留原密码",
                "parameters": [
                    {
                        "description": "设置",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SettingsResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "订阅列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Subscription"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "添加订阅并同步 qBittorrent",
                "parameters": [
                    {
                        "description": "订阅",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Subscription"
                        }
                    }
                }
            }
        },
        "/subscriptions/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "更新订阅并同步 qBittorrent",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "订阅 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "订阅",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Subscription"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "subscriptions"
                ],
                "summary": "删除订阅及 qBittorrent RSS 配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "订阅 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/subscriptions/{id}/broadcast-day": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "设置订阅放送星期",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "订阅 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "放送星期",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateBroadcastDayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Subscription"
                        }
                    }
                }
            }
        },
        "/subscriptions/{id}/sync": {
            "post": {
                "tags": [
                    "subscriptions"
                ],
                "summary": "重新同步订阅到 qBittorrent",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "订阅 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Subscription"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.CreateSubscriptionRequest": {
            "type": "object",
            "properties": {
                "customDirName": {
                    "type": "string"
                },
                "excludeRegex": {
                    "type": "string"
                },
                "regex": {
                    "type": "string"
                },
                "rssUrl": {
                    "type": "string"
                },
                "season": {
                    "type": "integer"
                }
            }
        },
        "model.LogResponse": {
            "type": "object",
            "properties": {
                "lines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.QBRSSSettings": {
            "type": "object",
            "properties": {
                "autoDownloadingEnabled": {
                    "type": "boolean"
                },
                "processingEnabled": {
                    "type": "boolean"
                },
                "refreshInterval": {
                    "type": "integer"
                }
            }
        },
        "model.QBTestResponse": {
            "type": "object",
            "properties": {
                "connected": {
                    "type": "boolean"
                },
                "version": {
                    "type": "string"
                },
                "webApiVersion": {
                    "type": "string"
                }
            }
        },
        "model.SettingsResponse": {
            "type": "object",
            "properties": {
                "defaultCategory": {
                    "type": "string"
                },
                "defaultExcludeRegex": {
                    "type": "string"
                },
                "downloadRoot": {
                    "type": "string"
                },
                "latestExcludeRegex": {
                    "type": "string"
                },
                "passwordSet": {
                    "type": "boolean"
                },
                "qbUrl": {
                    "type": "string"
                },
                "qbUsername": {
                    "type": "string"
                },
                "rssInterval": {
                    "type": "integer"
                }
            }
        },
        "model.Subscription": {
            "type": "object",
            "properties": {
                "bangumiId": {
                    "type": "integer"
                },
                "bangumiUrl": {
                    "type": "string"
                },
                "broadcastDay": {
                    "type": "string"
                },
                "broadcastDayOverride": {
                    "type": "string"
                },
                "broadcastStart": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "excludeRegex": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "officialUrl": {
                    "type": "string"
                },
                "posterUrl": {
                    "type": "string"
                },
                "rawTitle": {
                    "type": "string"
                },
                "regex": {
                    "type": "string"
                },
                "rssUrl": {
                    "type": "string"
                },
                "ruleName": {
                    "type": "string"
                },
                "saveDirName": {
                    "type": "string"
                },
                "savePath": {
                    "type": "string"
                },
                "season": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.UpdateBroadcastDayRequest": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string"
                }
            }
        },
        "model.UpdateSettingsRequest": {
            "type": "object",
            "properties": {
                "defaultCategory": {
                    "type": "string"
                },
                "defaultExcludeRegex": {
                    "type": "string"
                },
                "downloadRoot": {
                    "type": "string"
                },
                "qbPassword": {
                    "type": "string"
                },
                "qbUrl": {
                    "type": "string"
                },
                "qbUsername": {
                    "type": "string"
                },
                "rssInterval": {
                    "type": "integer"
                }
            }
        },
        "model.UpdateSubscriptionRequest": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "excludeRegex": {
                    "type": "string"
                },
                "regex": {
                    "type": "string"
                },
                "rssUrl": {
                    "type": "string"
                },
                "saveDirName": {
                    "type": "string"
                },
                "season": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Mikan qBittorrent RSS API",
	Description:      "qBittorrent RSS 管理工具 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
